Repository MateAcademy-FE-study/wild-tigers.github.io, pull requests merged in 2018-08, with the labels that each got.

#42 nunjucks added !important
  gulpfile.js
  src/pages/index.html
  src/templates/layout.html
  src/templates/partials/_features.html
  src/templates/partials/_footer.html
  src/templates/partials/_header.html
  src/templates/partials/_hire_us.html
  src/templates/partials/_history.html
  src/templates/partials/_packages.html
  src/templates/partials/_process.html
  src/templates/partials/_projects.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_team.html
  src/templates/partials/_welcome.html
Labels: enhancement

#43 fix if new gulp with nunjucks has errors
  gulpfile.js
  src/index.html
  src/scss/_footer.scss
  src/scss/_header.scss
  src/scss/_projects.scss
  src/scss/_team.scss
  src/scss/_variables.scss
  src/scss/_welcome.scss
  src/templates/layout.html
  src/templates/partials/_features.html
  src/templates/partials/_footer.html
  src/templates/partials/_header.html
  src/templates/partials/_hire_us.html
  src/templates/partials/_history.html
  src/templates/partials/_packages.html
  src/templates/partials/_process.html
  src/templates/partials/_projects.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_team.html
  src/templates/partials/_welcome.html
Labels: bug

#46 welcome 52%
  src/scss/_header.scss
  src/scss/_welcome.scss
  src/templates/partials/_header.html
Labels: enhancement

#58 history section
  src/img/png/macbook_2.png
  src/scss/_history.scss
  src/scss/main.scss
  src/templates/partials/_history.html
Labels: enhancement

#68 closes #61, add missing box shadow
  src/scss/_buttons.scss
Labels: bug fix

#63 optimize style format
  src/scss/_buttons.scss
Labels: enhancement

#70 add container padding-top
  src/scss/_container.scss
  src/scss/_footer.scss
  src/scss/_header.scss
  src/templates/partials/_footer.html
  src/templates/partials/_welcome.html
Labels: enhancement

#64 arrow for welcome
  src/scss/_welcome.scss
Labels: enhancement

#57 added change svg on hover
  src/scss/_features.scss
  src/templates/partials/_features.html
Labels: bug

#72 K what we do section
  src/scss/_services.scss
  src/scss/main.scss
  src/templates/partials/_services.html
Labels: enhancement

#79 packages closes #65
  src/scss/_buttons.scss
  src/scss/_normalize.scss
  src/scss/_packages.scss
  src/scss/_variables.scss
  src/scss/main.scss
  src/templates/partials/_packages.html
Labels: good first issue

#76 social icons fix
  src/scss/_footer.scss
  src/templates/layout.html
  src/templates/partials/_footer.html
Labels: bug fix

#67 draft for process section
  src/scss/_process.scss
  src/scss/_variables.scss
  src/templates/partials/_process.html
Labels: enhancement

#77 paddings and margins fixes
  src/scss/_buttons.scss
  src/scss/_container.scss
  src/scss/_hire.scss
  src/scss/_team.scss
  src/templates/partials/_team.html
Labels: bug fix

#78 some fixes
  src/scss/_buttons.scss
  src/scss/_container.scss
  src/scss/_hire.scss
  src/scss/_history.scss
  src/scss/_team.scss
  src/templates/partials/_history.html
  src/templates/partials/_projects.html
  src/templates/partials/_support.html
  src/templates/partials/_team.html
Labels: bug fix

#81 resave svg with wrong text align
  src/img/svg/big_pic/01_start.svg
  src/img/svg/big_pic/12_finish.svg
Labels: bug fix
