Repository MateAcademy-FE-study/wild-tigers.github.io, pull requests merged in 2018-09, with the labels that each got.

#85 slider
  src/img/png/iphone_slide_01.png
  src/img/png/iphone_slide_02.png
  src/img/png/iphone_slide_03.png
  src/img/png/macbook_slide.png
  src/img/png/macbook_slide_01.png
  src/img/png/macbook_slide_02.png
  src/img/png/macbook_slide_03.png
  src/scss/_welcome.scss
  src/templates/layout.html
  src/templates/partials/_welcome.html
Labels: enhancement

#91 burger menu
  src/scss/_header.scss
  src/templates/layout.html
  src/templates/partials/_header.html
Labels: enhancement

#94 navigation for horizontal screen orientation
  src/scss/_header.scss
Labels: enhancement

#92 K aos test
  gulpfile.js
  package.json
  src/js/aos.js
  src/scss/_buttons.scss
  src/scss/_features.scss
  src/scss/_history.scss
  src/scss/_services.scss
  src/scss/_variables.scss
  src/scss/_welcome.scss
  src/templates/layout.html
  src/templates/partials/_features.html
  src/templates/partials/_hire_us.html
  src/templates/partials/_history.html
  src/templates/partials/_packages.html
  src/templates/partials/_process.html
  src/templates/partials/_projects.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_welcome.html
Labels: enhancement

#96 fix for history title
  src/scss/_container.scss
  src/scss/_header.scss
  src/scss/_history.scss
  src/scss/main.scss
Labels: bug fix

#97 aos
  gulpfile.js
  src/js/_AOSconfig.js
  src/js/aos.js
  src/templates/layout.html
Labels: enhancement

#108 arrow pulsating
  src/scss/_services.scss
  src/templates/partials/_services.html
Labels: enhancement

#107 features section for small screens
  src/scss/_features.scss
Labels: enhancement

#106 add yellow border closes #93
  src/scss/_header.scss
  src/templates/partials/_header.html
Labels: enhancement

#105 change for all sections aos to fade-up
  src/templates/partials/_features.html
  src/templates/partials/_footer.html
  src/templates/partials/_hire_us.html
  src/templates/partials/_history.html
  src/templates/partials/_packages.html
  src/templates/partials/_projects.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_team.html
  src/templates/partials/_welcome.html
Labels: enhancement

#113 modal window
  src/js/script.js
  src/js/toTop.js
  src/pages/index.html
  src/scss/_buttons.scss
  src/scss/_modal.scss
  src/scss/_services.scss
  src/scss/main.scss
  src/templates/layout.html
  src/templates/partials/_modal.html
  src/templates/partials/_services.html
Labels: enhancement

#110 change svg to gif and add hover closes #109
  src/img/png/happy_clerk.gif
  src/img/svg/happy_clerk_lamp.svg
  src/scss/_history.scss
  src/templates/partials/_history.html
Labels: enhancement

#121 add pattern to history and process sections
  src/img/png/pattern.png
  src/scss/_history.scss
  src/scss/_process.scss
  src/scss/main.scss
Labels: enhancement

#124 pixel perfect adjustment
  src/scss/_header.scss
Labels: pixel perfect

#130 add meta description
  src/templates/layout.html
Labels: enhancement

#127 add blazy for biggest pics
  src/img/png/macbook_1_small.gif
  src/templates/partials/_hire_us.html
  src/templates/partials/_history.html
  src/templates/partials/_process.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_welcome.html
Labels: enhancement

#131 add aria-label
  src/templates/partials/_footer.html
  src/templates/partials/_header.html
  src/templates/partials/_modal.html
  src/templates/partials/_services.html
Labels: enhancement

#129 remove self-invoke for b-lazy
  src/templates/layout.html
Labels: bug fix

#134 fix #1-4 comments from Yura
  src/scss/_container.scss
  src/scss/_header.scss
  src/scss/_welcome.scss
  src/templates/partials/_header.html
  src/templates/partials/_welcome.html
Labels: bug fix

#139 fix for button in range 380 - 400 px
  src/scss/_hire.scss
Labels: bug fix

#138 fix for picture in history section
  src/scss/_history.scss
Labels: bug fix

#137 atomic class for uppercase
  src/scss/_buttons.scss
  src/scss/_general.scss
  src/scss/_header.scss
  src/scss/_services.scss
  src/scss/_welcome.scss
  src/templates/partials/_features.html
  src/templates/partials/_header.html
  src/templates/partials/_history.html
  src/templates/partials/_packages.html
  src/templates/partials/_process.html
  src/templates/partials/_projects.html
  src/templates/partials/_services.html
  src/templates/partials/_support.html
  src/templates/partials/_team.html
  src/templates/partials/_welcome.html
Labels: optimization

#135 fix #5 comment from Yura
  src/js/_AOSconfig.js
  src/js/aos.js
  src/js/script.js
  src/js/toTop.js
  src/templates/layout.html
  src/templates/partials/_header.html
  src/templates/partials/_packages.html
  src/templates/partials/_welcome.html
Labels: optimization
